version: "3.2"

services:
  store-BusinesRules:
    image: store-BusinesRules
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python3 app/main.py
    volumes:
      - ../:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app/main.py
    networks:
      - store-network

networks:
  store-network:
    external: true
